### ISSUE TITLE
windows defender says "BotIt Project.exe" is Trojan:Win32/Occamy.B ?

### ISSUE THREAD

**Issue by ychsiao168** [DizzyduckAR/BotIt#4]
Windows Defender says "BotIt Project.exe" is Trojan:Win32/Occamy.B ...
(both 0.1.7 and 0.2.2)

**Comment by DizzyduckAR** [comment]
We are aware of the issue.
In order to make 1 file download we compiled the download and update to botit project.exe.
Many systems will auto flag any compiled ahk exe.
Nothing to do with us and the issue is for all ahk users.

Since we always stay crystal clear we added the main source code to the download and update next to the exe.
User can view the code and see it's a simple dl and extract.
User can also run the botit project.ahk to avoid any use of EXE (ahk must be installed on system)

Also you can use any stock ahk EXE rename it to botit project.exe and it will run the ahk with the same name.

We choose months ago to stop fighting this totalvirus false detects. We are here to code and almost all the project runs uncompiled with stock ahk EXE next to it just to allow full control of everything!

So far AVG and mcfee green light the project.
If you scan it with them it will not trigger the detection.

In some cases user anti virus detect scrcpy core as a virus.
Pure Mambo Jambo. Biggest project on github..

**Comment by DizzyduckAR** [comment]
Update 27/10/2020:
all anti virus green light the project.
only windows defender keep claim the issue.

we are working with Microsoft support and provided the code and the github to clean this false claim.
they even change the trojan type lol. pure blindness by window defender..

**Comment by DizzyduckAR** [comment]
03/11/20:
we resent the app to Microsoft again.
it false detect Trojan:Win32/Wacatac.D8!ml (random stuff)

![chrome_uIyEszSD53](https://user-images.githubusercontent.com/52171360/97997945-30072d80-1df2-11eb-92d1-22c22b956874.png)

so while they check the app please use any other anti virus.
![chrome_67OmfoMFN5](https://user-images.githubusercontent.com/52171360/97998138-693f9d80-1df2-11eb-98b7-470638767637.png)


issue is we got ahk scrcpy and python exe.
i guess it all the red flags for them even when every part of it is stock github file..

**Comment by DizzyduckAR** [comment]
Microsoft is getting all Updates Before we Push.
This issue will stop.
